name:                haskell-and-elm
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/haskell-and-elm#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
  - README.md

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - blaze-html
  - constraints
  - containers
  - elmap
  - extensible
  - extensible-elmap
  - http-api-data
  - microlens
  - servant
  - servant-blaze
  - servant-elmap
  - servant-server
  - stm
  - text
  - transformers
  - unordered-containers

library:
  source-dirs: src
  ghc-options: -fno-warn-orphans

executables:
  server:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - haskell-and-elm
      - warp
    other-modules:
    - Orphans

tests:
  generate:
    source-dirs: app
    main: Generate.hs
    dependencies:
      - haskell-and-elm
      - process
    other-modules: []
