name:                haskell-and-elm
version:             0.1.0.0
ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - containers
  - elm-export
  - http-api-data
  - servant
  - servant-ede
  - servant-elm
  - servant-server
  - stm
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Todo
  other-modules: []

executables:
  server:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - haskell-and-elm
      - warp
    other-modules: []

tests:
  generate:
    source-dirs: app
    main: Generate.hs
    dependencies:
      - haskell-and-elm
      - shelly
    other-modules: []
