name: Build

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ["8.8.3"]
    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1.1.2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}-v1
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: matsubara0507/setup-stack@master
    - name: Remove GHC in .stack
      run: rm -rfd ~/.stack/programs

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Run test
      run: stack --system-ghc --no-terminal test --no-run-benchmarks --no-haddock-deps
